[package]
name = "sway-move-here"
version = "0.1.0"
authors = ["Stas Rudakou <stas@garage22.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
